### ISSUE TITLE
Add "folder" option to several scripts

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#11]
It would be good to include an option to load an entire folder of files with some of the scripts, particularly mgmotion.

**Comment by emoninet2** [comment]
https://github.com/fourMs/MGT-matlab/pull/23
load all files from folder supported for mgmotion, mgmotionhistory and mgmotionaverage.

**Comment by alexarje** [comment]
I cannot see to get that working. How do you call that? mgmotion('Folder')?

**Comment by emoninet2** [comment]
to load all video files from an entire directory

mgmotion_loadMultiple, mgmotionhistory_loadMultiple, mgmotionaverage_loadMultiple. 

the examples can be found in the examples.m file

'_loadMultiple' may not sound like the best naming convention. I will change it to '_loadDir' or anything else you have in mind.

**Comment by alexarje** [comment]
Ah, I see. But for convenience, do you think it would be possible to add this to the main functions, something like mgmotion('Folder') would ask for a directory and then process all relevant files there?

**Comment by emoninet2** [comment]
Fix in https://github.com/fourMs/MGT-matlab/pull/25. 

mgmotion, mgmotionaverage and mgmotionhistory now supports loading a single file or multiple files from a folder in the same function.
