### ISSUE TITLE
Problem with optical flow

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#13]
Issues when running mgmotion with opticalflow argument:

>mgmotion(arg,'OpticalFlow');
>The motion video is created with name alis9-radd.avi_flow.avi
>Reference to non-existent field 'nframe'.
>Error in mgmotionplot (line 24)
>f.video.timeseries=1:f.video.nframe;
>Error in mgmotion (line 478)
>mgmotionplot(mg);

**Comment by alexarje** [comment]
This seems to be an issue on all platforms after all

**Comment by emoninet2** [comment]
nframe value previously was set only for 'DIff' condition and not for 'OpticalFlow'. Add 

`mg.video.nframe = v.FrameCount `

at line after 

`disp(['The motion video is created with name ',newfile]); `

inside the 'OpticalFlow' condition.

Fixed in https://github.com/fourMs/MGT-matlab/pull/17
