### ISSUE TITLE
Motiongram issue in demo files

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#14]
There is an error in “plots the whole motion grams” function in both mgdemo1.m and  mgdemo2.m. 

It seems that the gramx and gramy functions remained undefined.

**Comment by emoninet2** [comment]
Fixed: mgmotion outputs to 

> mg.video.gram.x 

and not 

> mg.video.gram.gramx

Fixed in https://github.com/fourMs/MGT-matlab/pull/17

**Comment by emoninet2** [comment]
Previously the frame loop inside mgvideoplot never ended even after processing all the frames. 

use the condition after incrementing 'i' to detect end frame and break the loop.  

```
if(  (round((i/30) * mgmotion.mocap.freq) + 1) > mgmotion.mocap.nFrames)
break;
end
```

fixed in https://github.com/fourMs/MGT-matlab/pull/17
