### ISSUE TITLE
Add skipframe functionality

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#16]
This is implemented in MGT-python, and is based on setting number of frames to skip. Greatly decreases processing.

**Comment by emoninet2** [comment]
Does the variable _'frameInterval'_  in mgmotion determine the skip of frames?

**Comment by emoninet2** [comment]
added feature in https://github.com/fourMs/MGT-matlab/pull/17

**Comment by alexarje** [comment]
Great to have it implemented in mgmotion. Would it make sense to implement in in mgmotionaverage and mgmotionhistory as well? These can be generated from the exported motion video, but sometimes it would be useful to have it implemented in the functions as well.

**Comment by emoninet2** [comment]
feature added in https://github.com/fourMs/MGT-matlab/pull/23
