### ISSUE TITLE
Dependency on MathWorks toolboxes

### ISSUE THREAD

**Issue by olivierlar** [fourMs/MGT-matlab#2]
When running examples.m on my computer, some commands did not work because some toolboxes from MathWorks, unspecified in the documentation, were not in my installation:
- mgmotion(..., 'OpticalFlow') requires Computer Vision System Toolbox
- mgmotionhistory requires Image Processing Toolbox

Might be useful to indicate these dependencies in the documentation?

**Comment by alexarje** [comment]
Thanks. Yes, have added it to the documentation now.
