### ISSUE TITLE
Unify progress bars

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#20]
At the moment all the main functions use different types of progress bars. It would be nice to clean it up so that they use the same type. The pop-up looks nice, but how does it work if matlab is run only in the terminal? Perhaps more robust to use a simpler, inline version?

**Comment by emoninet2** [comment]
added simple text based progress bar for mgmotion in https://github.com/fourMs/MGT-matlab/pull/22

**Comment by alexarje** [comment]
Nice. Have removed the waitbar now. For some reason I get an error with the textprogressbar in the opticalflow part of the code (l.324). Have reverted to the waitbar there.

**Comment by emoninet2** [comment]
Fixed in https://github.com/fourMs/MGT-matlab/pull/25. All the main functions now uses progmeter.

**Comment by alexarje** [comment]
Cool, thanks.
