### ISSUE TITLE
Problem saving color images from mgmotionaverage

### ISSUE THREAD

**Issue by alexarje** [fourMs/MGT-matlab#8]
The option to save color images using mg structures in mgmotionaverage does not work. Strange, looks like it is using similar code to mgmotion.

**Comment by emoninet2** [comment]
Fixed. 'mg' was previously not pointing to f. 

Fixed in https://github.com/fourMs/MGT-matlab/pull/17

**Comment by alexarje** [comment]
It would be good to have a 'color' option also for this function (similar to mgmotion and mgmotionhistory).

**Comment by emoninet2** [comment]
Fixed color feature in mgmotionhistory and mgmotionaverage as well in https://github.com/fourMs/MGT-matlab/pull/22
